log:
  level: debug
server:
  grpc:
    host: 
    port: 50051
  http: 
    host: 
    port: 8088
database:
  type: memory
  sql:
    dsn: host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable