log:
  level: debug
server:
  grpc:
    host: localhost
    port: 50051
  http: 
    host: localhost
    port: 8080
database:
  type: memory
  sql:
    dsn: host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable