log:
  level: debug
server:
  proto: grpc
  host: localhost
  port: 50051
database:
  type: memory
  sql:
    dsn: host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable