log:
  level: debug
server:
  grpc:
    host: calendar
    port: 50051
  http: 
    host: calendar
    port: 8088
scheduler:
  checkPeriod: 1
publisher:
  uri: amqp://guest:guest@rabbit:5672/
  exchange:     calendar-exchange
  exchangeType: direct
  routingKey:   calendar-key
  reliable:     true
