log:
  level: debug
consumer:
  uri:          amqp://guest:guest@rabbit:5672/
  exchange:     calendar-exchange
  exchangeType: direct
  queue:        calendar-queue
  bindingKey:   calendar-key
  consumerTag:  calendar-consumer
  lifetime:     0
