version: "3"

networks:
  rabbit:
    driver: bridge
  db:
    driver: bridge
  calendar:
    driver: bridge

services:
  calendar:
    build:
      dockerfile: build/Dockerfile.calendar
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8088:8088"
      - "50051:50051"
    expose:
      - 8088
      - 50051
    environment:
      REG_SERVICE_DB_DSN: "postgres://test:test@postgres:5432/exampledb?sslmode=disable"
    networks:
       - calendar
       - db

  scheduler:
    build:
      dockerfile: build/Dockerfile.scheduler
    depends_on:
      - calendar
      - rabbit
    restart: on-failure
    environment:
      SHEDULER_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - calendar
      - rabbit

  sender:
    build:
      dockerfile: build/Dockerfile.sender
    depends_on:
      - rabbit
    restart: on-failure
    environment:
      SENDER_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - rabbit

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: exampledb
    volumes:
      # https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L145
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - db

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
      - 5672
    volumes:
      - ./configs/rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./configs/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbit

